# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: continuumio/miniconda3:latest

before_script:
  - python -V  # Print out python version for debugging
  - export PIP_CACHE_DIR="/opt/cache/pip"
  - conda env create -n wesnake -f environment.yaml
  - conda init
  - conda activate wesnake
  - pip install git+https://github.com/testcontainers/testcontainers-python.git

test:
  script:
    - python -m pytest

run:
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
