wes_server:
    type: dict
    required: true
    schema:
        host:
            type: string
            required: true
        port:
            type: integer
            required: true
        debug:
            type: boolean
            required: false

mongo_server:
    type: dict
    required: false
    schema:
        host:
            type: string
            required: true
        port:
            type: integer
            required: true

debug:
    type: boolean
    required: true