wes_server:
    type: dict
    required: true
    schema:
        host:
            type: string
        port:
            type: integer
        debug:
            type: boolean

mongo_server:
    type: dict
    required: false
    schema:
        host:
            type: string
        port:
            type: integer

debug:
    type: boolean
    required: true