version: '3'

networks:
  backend:
    driver: overlay

services:

  rest:
    hostname: weskit
    image: ${WESNAKE_IMAGE}
    environment:
      WESNAKE_CONFIG: /home/weskit/config.yaml
      WESNAKE_LOG_CONFIG:
      WESNAKE_VALIDATION_CONFIG:
      WESNAKE_DATABASE_URL: mongodb://database:27017
      WESNAKE_DATA: /weskit_data
      RESULT_BACKEND: redis://result_broker:6379
      BROKER_URL: redis://result_broker:6379
      FLASK_APP: weskit
    volumes:
      - ${WESNAKE_DATA}:/weskit_data
      - ${WESNAKE_CONFIG}:/home/weskit/config.yaml:ro
      - ${SHARED_FILESYSTEM_ROOT}:/data
    networks:
      - backend
    working_dir: /weskit
    entrypoint: ["bash", "-i", "-c"]
    command: ["conda activate weskit && pip install ./ && flask run --host=0.0.0.0 --port=5000"]
    ports:
      - 5000:5000

  database:
    image: mongo:4.2.3
    volumes:
      - ${SHARED_FILESYSTEM_ROOT}:/var/lib/mongodb
    networks:
      - backend
    ports:
      - 27017:27017

  result_broker:
    image: redis:6.0.1-alpine
    volumes:
      - ${REDIS_CONFIG}:/usr/local/etc/redis/redis.conf:ro
      - ${SHARED_FILESYSTEM_ROOT}:/data
    networks:
      - backend
    ports:
      - 6379:6379

  # Workers are probably better started more dynamically, e.g. in LSF cluster, Docker swarm or Kubernetes.
  worker1:
    image: ${WESNAKE_IMAGE}
    environment:
      RESULT_BACKEND: redis://result_broker:6379
      BROKER_URL: redis://result_broker:6379
    working_dir: /weskit
    entrypoint: ["bash", "-i", "-c"]
    command: ["conda activate weskit; celery worker --loglevel DEBUG --concurrency 1 --app weskit.tasks.celery_worker.celery_app"]
    volumes:
      - ${WESNAKE_DATA}:/weskit_data
      - ${SHARED_FILESYSTEM_ROOT}:/data
    networks:
      - backend

