version: '3.9'

networks:
  backend:
    driver: overlay
    driver_opts:
      encrypted: "false"

volumes:
  mongodb-configdb:
  mongodb-data:
  redis-data:

services:

  rest:
    image: ${WESKIT_IMAGE}
    secrets:
      - weskit.key
      - weskit.crt
    depends_on:
      - database
      - result_broker
    environment:
      WESKIT_CONFIG: /home/weskit/config.yaml
      WESKIT_LOG_CONFIG: /home/weskit/log-config.yaml
      WESKIT_VALIDATION_CONFIG:
      WESKIT_DATABASE_URL: mongodb://database:${MONGODB_PORT:-27017}
      WESKIT_DATA: /data
      RESULT_BACKEND: redis://result_broker:${REDIS_PORT:-6379}
      BROKER_URL: redis://result_broker:${REDIS_PORT:-6379}
      FLASK_APP: weskit
    volumes:
      - ${WESKIT_CONFIG}:/home/weskit/config.yaml:ro
      - ${WESKIT_LOG_CONFIG}:/home/weskit/log-config.yaml:ro
      - ${WESKIT_DATA}:/data
      - ./users.yaml:/weskit/users.yaml:ro
    networks:
      - backend
    working_dir: /weskit
    entrypoint: ["bash", "-i", "-c"]
    command: [ "conda activate weskit && pip install ./ && ln -s /run/secrets/weskit.* /weskit/uWSGI_Server/certs/  && uwsgi --ini /weskit/uWSGI_Server/uwsgi.ini" ]
    ports:
      - "${WESKIT_PORT:-5000}:5000"
    # healthcheck:
    #   test: ["CMD-SHELL", "(curl -f http://localhost:5000/gh4gh/wes/v1/service-info | grep '\"environment\": \"development\"') && echo 'OK'"]
    #   interval: 10s
    #   timeout: 2s
    #   retries: 3

  database:
    image: mongo:4.2.3
    volumes:
      - mongodb-data:/data/db
      - mongodb-configdb:/data/configdb
    networks:
      - backend
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    deploy:
      # Deploy on the manager only, because the data volume is local on that machine
      placement:
        constraints: [node.role == manager]

  result_broker:
    image: redis:6.0.1-alpine
    volumes:
      - ${REDIS_CONFIG}:/usr/local/etc/redis/redis.conf:ro
      # Used for persistence of the broker data.
      - redis-data:/data
    networks:
      - backend
    ports:
      - "${REDIS_PORT:-6379}:6379"
    deploy:
      # Deploy on the manager only, because the data volume is local on that machine
      placement:
        constraints: [node.role == manager]

  worker:
    image: ${WESKIT_IMAGE}
    depends_on:
      - result_broker
    environment:
      RESULT_BACKEND: redis://result_broker:${REDIS_PORT:-6379}
      BROKER_URL: redis://result_broker:${REDIS_PORT:-6379}
    working_dir: /weskit
    entrypoint: ["bash", "-i", "-c"]
    command: ["conda activate weskit && celery worker --loglevel DEBUG --concurrency 1 --app weskit.tasks.celery_worker.celery_app"]
    volumes:
      - ${WESKIT_DATA}:/data
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
#      placement:
#        # Limit the number of replicas. Probably the memory consumption is limiting.
#        max_replicas_per_node: 32


secrets:
  weskit.key:
    file: uWSGI_Server/certs/weskit.key
  weskit.crt:
    file: uWSGI_Server/certs/weskit.crt
