name: weskit
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - celery=5.0.5
  - cerberus=1.3.2
  - flake8=3.8.4
  - flask=1.1.2
  - jsonschema=3.2.0
  - pip=20.3.3
  - pylint=2.4.4
  - pymongo=3.11.2
  - pytest=6.2.1
  - pytest-celery=0.0.0a1
  - python=3.7.6
  - pyyaml=5.3.1
  - requests=2.25.1
  - snakemake=5.30.2
  - vine=1.3.0
  - flask-jwt-extended=3.25.0
  - uwsgi=2.0.19.1
  - nextflow=20.10.0
  - pip:
     - testcontainers==3.0.0
     - redis==3.5.1

