name: weskit
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - celery=5.0.5
  - cerberus=1.3.2
  - click=7.1.2
  - flake8=3.8.4
  - flask=1.1.2
  - jsonschema=3.2.0
  - pip=20.3.3
  - pylint=2.4.4
  - pymongo=3.11.2
  - pytest=6.2.1
  - pytest-celery=0.0.0a1
  - pytest-cov=2.11.1
  - mccabe=0.6.1
  - python=3.7.6
  - pyyaml=5.3.1
  - requests=2.25.1
  - snakemake=6.10.0
  - vine=1.3.0
  - flask-jwt-extended=3.25.0
  - uwsgi=2.0.19.1
  - pymysql=1.0.2
  - bioconda::nextflow=21.04.0
  - procps-ng=3.3.17             # For nextflow default_workflow_engine_parameters test
  - bandit=1.7.0
  - asyncssh=2.7.2
  - singularity=3.7.1
  - flufl.lock=6.0
  - pip:
     - testcontainers==3.0.0
     - redis==3.5.1
     - rfc3339==6.2
     - trs-cli==0.7.0

