name: wesnake
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - celery=4.4.2
  - cerberus=1.3.2
  - flake8=3.8.4
  - flask=1.1.2
  - pip=20.3.3
  - pylint=2.4.4
  - pymongo=3.11.2
  - pytest=6.2.1
  - python=3.7.6
  - pyyaml=5.3.1
  - redis=5.0.3
  - snakemake=5.30.2
  - vine=1.3.0
  - pip:
     - testcontainers==3.0.0
     - redis==3.5.1

