version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "%(asctime)s %(levelname)s %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%SZ"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        filename: wesnake.log
root:
    handlers: [file]
    level: INFO
loggers:
    default:
        level: ERROR
        handlers: [file, console]
        propagate: false
    test:
        level: DEBUG
        handlers: [console]
        propagate: false
