version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "%(asctime)s %(levelname)s %(message)s"
        datefmt: "%Y-%m-%dT%H:%M:%SZ"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout
    file:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        filename: app.log
root:
    handlers: [file]
    level: INFO
loggers:
    other:
        level: INFO
        handlers: [file]
        propagate: false