version: '3'

services:
    wesnake:
        image: wesnake:0.0.1
#        restart: unless-stopped
#        depends_on:
#          - database
#          - redis
#          - celery_worker
        volumes:
          - /home/twardzso/workspaces/wesnake:/wesnake
        networks:
            - backend
        ports:
            - "4080:4080"
#        command: sleep 3600
        command: bash -c "cd /wesnake; pip install .; wesnake --config /wesnake/scratch/config.yaml"
    
    database:
        image: mongo:4.2.3
#        restart: unless-stopped
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: root
#            MONGO_INITDB_ROOT_PASSWORD: example_database
#        volumes:
#            - ${MONGODB_VOLUME}:/var/lib/mongodb
        networks:
            - backend
        ports:
            - "27017:27017"
#    
    redis:
        image: redis:latest
        networks:
            - backend
        ports:
            - "6379:6379"
#    
    celery_worker:
        depends_on:
            - redis
            - wesnake
        image: wesnake:0.0.1
        volumes:
            - /home/twardzso/workspaces/wesnake:/wesnake
        networks:
            - backend
        command: bash -c "cd /wesnake; celery worker -A ga4gh.wes.celery_worker.celery"

networks:
    backend:
        driver: overlay
#    frontend:
#        driver: overlay

#volumes:
#    # For NFS volumes see https://docs.docker.com/compose/compose-file/compose-file-v2/#driver_opts
#    shared:
#        driver: local
#        driver_opts:
#            o: bind
#            type: none
#            device: ${SHARED_FILESYSTEM_ROOT}
