# Compare GA4GH WES-API
run_request:
  workflow_params:
    required: true
    type: string     # Type: JSON string
  workflow_type:
    required: true
    type: string
  workflow_type_version:
    required: true
    type: string
  tags:
    required: false
    type: dict
  workflow_engine_parameters:
    # Note: The schema is the same as in default_workflow_engine_parameters
    type: list
    required: false
    schema:
      type: dict
      required: true
      schema:
        name:
          type: string
          required: true
        type:
          type: string
          required: true
        default_value:
          type: string
          required: true
        workflow_engine:
          type: string
          required: true
  workflow_url:
    required: true
    type: string
