TESTING:
  type: boolean
ENV:
  type: string
  allowed:
    - production
    - development
DEBUG:
  type: boolean

require_workdir_tag:
  type: boolean
  required: true

static_service_info:
  type: dict
  required: true
  schema:
    workflow_type_versions:
      type: dict
      required: true
      valuesrules:
        type: dict
        required: true
        schema:
          workflow_type_version:
              type: list
              required: true
              schema:
                type: string
    supported_filesystem_protocols:
      type: list
      required: true
      schema:
        type: string
    workflow_engine_versions:
      type: dict
      required: true
      schema:
        snakemake:
          type: string
        nextflow:
          type: string
    default_workflow_engine_parameters:
      type: dict
      required: false
      keysrules:
        allowed:
          - snakemake
          - nextflow
      valuesrules:
        type: dict
        required: true
        valuesrules:
          type: dict
          schema:
            type:
              type: string
              required: true
            default_value:
              type: string
              required: true
    auth_instructions_url:
      type: string
      required: true
    contact_info_url:
      type: string
      required: true
    tags:
      type: dict
      required: false
      valuesrules:
        type: string


login:
  type: dict
  required: false
  schema:
    enabled:
      type: boolean
      required: true

    jwt:
      type: dict
      required: false
      schema:
        JWT_COOKIE_SECURE:
          type: boolean
          required: true
        JWT_TOKEN_LOCATION:
          type: list
          required: true
        JWT_ALGORITHM:
          type: string
          required: true
        JWT_DECODE_AUDIENCE:
          type: string
          required: true
        JWT_IDENTITY_CLAIM:
          type: string
          required: true
        JWT_ACCESS_COOKIE_PATH:
          type: string
          required: true
        JWT_REFRESH_COOKIE_PATH:
          type: string
          required: true
