TESTING:
  type: boolean
ENV:
  type: string
  allowed:
    - production
    - development
DEBUG:
  type: boolean

require_workdir_tag:
  type: boolean
  required: true

static_service_info:
  type: dict
  required: true
  schema:
    id:
      type: string
      required: true
    name:
      type: string
      required: true
    type:
      type: dict
      required: true
      schema:
        group:
          type: string
          required: true
        artifact:
          type: string
          required: true
        version:
          type: string
          required: true
    description:
      type: string
      required: false
      default: ""
    organization:
      type: dict
      required: true
      schema:
        name:
          type: string
          required: true
        url:
          type: string
          required: true
    contact_url:
      type: string
      required: false
      default: "mailto:unknown"
    documentation_url:
      type: string
      required: false
      default: "https://gitlab.com/one-touch-pipeline/weskit/documentation/-/wikis/home"
    created_at:
      type: datetime
      required: false
      default: 2021-01-01
    updated_at:
      type: datetime
      required: false
      default: 2021-01-01
    environment:
      type: string
      required: false
      default: unknown
    version:
      type: string
      required: true
    workflow_type_versions:
      type: dict
      required: true
      valuesrules:
        type: dict
        required: true
        schema:
          workflow_type_version:
              type: list
              required: true
              schema:
                type: string
    supported_filesystem_protocols:
      type: list
      required: true
      schema:
        type: string
    workflow_engine_versions:
      type: dict
      required: true
      schema:
        snakemake:
          type: string
        nextflow:
          type: string
    default_workflow_engine_parameters:
      type: dict
      required: false
      schema:              # workflow engine names

        nextflow:
          type: dict       # engine version tags
          required: true
          valuesrules:
            type: dict
            required: true
            schema:
              env: &envType            # environment variables
                type: dict
                default: {}
                valuesrules:
                  type: string
              command: &parameterType     # see `nextflow help`
                type: list
                default: []
                valuesrules:
                  type: dict
                  schema:
                    name:
                      required: true
                      type: string
                    value:
                      required: false
                      type: string
              run:  *parameterType        # see `nextflow help run`

        snakemake:
          type: dict       # engine version tags
          required: true
          valuesrules:
            type: dict
            required: true
            schema:
              env: *envType             # environment variables
              command: *parameterType   # snakemake command arguments

    auth_instructions_url:
      type: string
      required: true
    tags:
      type: dict
      required: false
      valuesrules:
        type: string


login:
  type: dict
  required: false
  schema:
    enabled:
      type: boolean
      required: true

    jwt:
      type: dict
      required: false
      schema:
        JWT_COOKIE_SECURE:
          type: boolean
          required: true
        JWT_TOKEN_LOCATION:
          type: list
          required: true
        JWT_ALGORITHM:
          type: string
          required: true
        JWT_DECODE_AUDIENCE:
          type: string
          required: true
        JWT_IDENTITY_CLAIM:
          type: string
          required: true
        JWT_ACCESS_COOKIE_PATH:
          type: string
          required: true
        JWT_REFRESH_COOKIE_PATH:
          type: string
          required: true
