TESTING:
  type: boolean
ENV:
  type: string
  allowed:
    - production
    - development
DEBUG:
  type: boolean
wes_server:
  type: dict
  required: true
  schema:
    host:
      type: string
      required: true
    port:
      type: integer
      required: true
    debug:
      type: boolean
      required: false
mongo_server:
  type: dict
  required: false
  schema:
    host:
      type: string
      empty: true
      required: true
    port:
      type: integer
      empty: true
      required: true

static_service_info:
  type: dict
  required: true
  schema:
    workflow_type_versions:
      type: dict
      required: true
      schema:
        Snakemake:
          type: dict
          required: true
          schema:
            workflow_type_version:
                type: list
                required: true
                schema:
                  type: string
    supported_filesystem_protocols:
      type: list
      required: true
      schema:
        type: string
    workflow_engine_versions:
      type: dict
      required: true
      schema:
        Snakemake:
          type: string
    default_workflow_engine_parameters:
      type: list
      required: true
      schema:
        type: dict
        required: true
        schema:
          name:
            type: string
            required: true
          type:
            type: string
            required: true
          default_value:
            type: string
            required: true
    auth_instructions_url:
      type: string
      required: true
    contact_info_url:
      type: string
      required: true
    tags:
      type: dict
      required: false
      valuesrules:
        type: string

